# Generated by Django 4.2 on 2023-05-03 04:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Mainpage', '0002_rename_description_project_app_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='iOSProject',
        ),
    ]
