# Generated by Django 4.2 on 2023-05-03 04:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Mainpage', '0003_rename_project_iosproject'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='iOSProject',
            new_name='IOS_Project',
        ),
    ]
