# Generated by Django 4.2 on 2023-05-03 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iOSProjects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='description',
            new_name='app_description',
        ),
    ]
